apiVersion: v1
kind: Service
metadata:
  name: ms-pacientes
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /patients/health
spec:
  selector:
    app: ms-pacientes
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3333
    nodePort: 30004
