apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-ms-pacientes
spec:
  provider: aws
  secretObjects:
  - data:
    - key: urlPacientes
      objectName: urlPacientes
    secretName: documentdb-secret-pacientes
    type: Opaque
  parameters:
    objects: |
        - objectName: "arn:aws:secretsmanager:us-east-1:851725345801:secret:documentdbcredentials-gxwTek"
          objectType: "secretsmanager"
          jmesPath:
            - path: "urlPacientes"
              objectAlias: urlPacientes
